import Header from '@/components/Header'
import { Metadata } from 'next'
import { FC, ReactNode } from 'react'
import '../styles/globals.scss'
import ReduxProvider from '@/redux/provider'

interface IRootLayout {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}

export default RootLayout
