import { Metadata } from "next";
import { FC, ReactNode } from "react";

interface IRootLayout {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="en">
            <body className="">{children}</body>
        </html>
    );
};

export default RootLayout;
