import Header from '@/components/Header'
import { Metadata } from 'next'
import { FC, ReactNode } from 'react'
import '@/styles/globals.scss'
import '@/styles/button.scss'
import ReduxProvider from '@/redux/provider'
import Image from 'next/image'
import background from '../public/images/background.png'

interface IRootLayout {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        <ReduxProvider>{children}</ReduxProvider>
        <Image
          src={background}
          alt="sdf"
          width={400}
          height={100}
          className="background-img"
        />
      </body>
    </html>
  )
}

export default RootLayout
